# Generated by Django 3.2.3 on 2021-06-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='pricipal',
            new_name='principal',
        ),
    ]
